### ISSUE TITLE
Add max zoom limit

### ISSUE THREAD

**Issue by actuallyduck** [tom-mohr/particle-life-app#13]
As said in the title it would be a nice addition to add a max zoom limit.
Maybe the limit could be when the entire map is the size of the cursor.

Isn't it useless to have so much zoom? 
(It's there somewhere)
![image](https://user-images.githubusercontent.com/122576084/217366244-007b5164-9e25-4eac-a529-fed1d9ee0e2c.png)

**Comment by tom-mohr** [comment]
Sounds good. Having a max zoom factor at something like 0.1 would be nice. I think this is low priority though, so I won't implement this myself in the next time.

**Comment by karolstawowski** [comment]
Hi, can I do a pull request with a max zoom limit feature?

**Comment by tom-mohr** [comment]
Yes, sure! Just make one and I'll take a look at it :) if you don't know how to make one, just ask in the #dev channel on Discord

**Comment by karolstawowski** [comment]
Here's a pull request: #16.

Waiting for your thoughts on it 😄

**Comment by VaderFuntime** [comment]
Also a max zoom out would be good... found myself zooming out and losing all of my particles
