### ISSUE TITLE
Please add '=' key for zooming in

### ISSUE THREAD

**Issue by niels747** [tom-mohr/particle-life-app#6]
I really love this awesome implementation! Nice job!
Please add '=' key for zooming in, since a keyboard without a numpad doesn't have a seperate '+' key.
Or please tell me any other way to zoom in...

**Comment by tom-mohr** [comment]
Thank you :)
Zooming is also possible with the mouse wheel. Here's a list of all controls: https://particle-life.com/app/docs#shortcuts
I assume you have a keyboard layout like this? https://upload.wikimedia.org/wikipedia/commons/d/da/KB_United_Kingdom.svg
Are you currently able to zoom in by pressing "Shift" and "+"? I agree it would make sense then to add the "=" key for zooming in.

**Comment by tom-mohr** [comment]
Implemented by #18
