### ISSUE TITLE
GUI has strange overflow bug when using "advanced GUI" and scrolling in the sidebar

### ISSUE THREAD

**Issue by tom-mohr** [tom-mohr/particle-life-app#7]
Problem:
- the different widgets in the UI on the left sometimes overlap
![image](https://user-images.githubusercontent.com/24864629/214442620-6b8fd572-835d-4c9c-88c6-e6f5f8e2b877.png)

Steps to reproduce:
- start the app
- press `F11` to go to window mode
- press `a` to enable advanced mode
- scroll down in the UI on the left

This probably has something to do with how _ImGuiBarGraph.java_ is using [ImGui](https://github.com/ocornut/imgui/).

**Comment by jroscoe5** [comment]
Did this get fixed or is it not consistently reproducible? Was trying all sorts of window sizes with both the exe and building from source but have not been able to reproduce haha

**Comment by tom-mohr** [comment]
Hm, I'm still able to reproduce it and nobody tried to fix it yet. Maybe people who see this can react to this comment with
- 😕 if they are able to reproduce the bug
- 🎉 if they are unable to reproduce the bug
